---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-deploy
  namespace: dev
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 100
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
        version: "v1.0"
    spec:
      containers:  
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80           



