---
apiVersion: v1
kind: Pod
metadata: 
  name: httpd-twice
spec:
  containers:
    - name: httpd1
      image: httpd2.4
      ports:
        ContainerPort: 80
    - name: httpd2
      image: httpd2.4
      ports:
        ContainerPort: 80
        