apiVersion: v1
kind: Pod
metadata:
  name: trail4
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk17
      resources:
        limits:
          cpu: 1000m 
          memory: 1Gi

      