apiVersion: v1
kind: Pod
metadata: 
  name: trail5
spec:
  restartPolicy: OnFailure
  initContainers: 
     - name: init1
       image: alpine
       args:
         - sleep
         - 10s
  initContainers:
     - name: init2
       image: alpine
       args:
         - sleep
         - 10s
  initContainers:
     - name: init3
       image: alpine
       args:
         - sleep
         - 10s        
  containers:
    - name: httpd
      image: httpd
      resources: 
        limits:
          cpu: 1000m
          memory: 0.5Gi
  containers:
    - name: nginx
      image: ngnix
      resources: 
        limits:
          cpu: 1000m
          memory: 0.5Gi
  containers:
    - name: nginx2
      image: nginx
      resources: 
        limits:
          cpu: 1000m
          memory: 0.5Gi     