---
apiVersion: v1
kind: Pod
metadata:
  name: trail6
  labels:
    env: dev
    app: ngnix
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
