---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trail3-deploy
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate:  
      maxSurge: 25%
      maxUnavailable: 25%
  template :
    metadata:
      labels:
        app: spc
        env: dev
        version: "v3.4.0" 
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080

