---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: nodePort
  selector:
    app: httpd
  ports:
    - name: apache
      port: 80 
      targetPort: 80
      nodePort: 30000


