---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail2-rs
  labels: 
    name: exercise1
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchExpressions:
      - key: activity
        operator: In
        values:
          - exercise1
          - exercise2
  template:
    metadata:
      labels:
        activity: exercise1
    spec:
      containers:
        - name: alpine
          image: alpine

      
