---
apiVersion: v1
kind: ReplicationController
metadata:
  name: trail3-rc
  labels:
    name: trail3
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx


  
