---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trail4-deploy
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      activity: exercise1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  template:
    metadata:
      name: alpine 
      labels:
        activity: exercise1 
    spec:
      containers:
        - name: alpine
          image: alpine 
          args: 
            - sleep
            - "1d"
          ports:
            - containerPort: 8080    
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits: 
              cpu: 500m
              memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: alpine-svc
spec:
  type: NodePort
  selector:
    activity: exercise1
  ports:
    - name: alpine
      port: 8080
      targetPort: 8080
      nodePort: 30001
     