---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: trail3-deploy
  labels:
    app: nginx
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: nginx   
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx 
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi  
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /admin
              port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: check-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: nginx
      targetPort: 80
      port: 80


